SET IDENTITY_INSERT UITerms ON;
INSERT INTO UITerms (UITermId, InternalName) VALUES(1, 'Classification');
INSERT INTO UITerms (UITermId, InternalName) VALUES(2, 'Id');
INSERT INTO UITerms (UITermId, InternalName) VALUES(3, 'Name');
INSERT INTO UITerms (UITermId, InternalName) VALUES(4, 'Create new classification');
INSERT INTO UITerms (UITermId, InternalName) VALUES(5, 'Add');
INSERT INTO UITerms (UITermId, InternalName) VALUES(6, 'Add language');
INSERT INTO UITerms (UITermId, InternalName) VALUES(7, 'Add values');
INSERT INTO UITerms (UITermId, InternalName) VALUES(8, 'Alphabetically');
INSERT INTO UITerms (UITermId, InternalName) VALUES(9, 'Back to classification levels');
INSERT INTO UITerms (UITermId, InternalName) VALUES(10, 'Back to classification values');
INSERT INTO UITerms (UITermId, InternalName) VALUES(11, 'Back to classifications');
INSERT INTO UITerms (UITermId, InternalName) VALUES(12, 'Can link');
INSERT INTO UITerms (UITermId, InternalName) VALUES(13, 'Cancel');
INSERT INTO UITerms (UITermId, InternalName) VALUES(14, 'Classification languages');
INSERT INTO UITerms (UITermId, InternalName) VALUES(15, 'Classification levels');
INSERT INTO UITerms (UITermId, InternalName) VALUES(16, 'Classification value languages');
INSERT INTO UITerms (UITermId, InternalName) VALUES(17, 'Content type');
INSERT INTO UITerms (UITermId, InternalName) VALUES(18, 'Create new classification level');
INSERT INTO UITerms (UITermId, InternalName) VALUES(19, 'Create new value');
INSERT INTO UITerms (UITermId, InternalName) VALUES(20, 'Date level');
INSERT INTO UITerms (UITermId, InternalName) VALUES(21, 'Delete');
INSERT INTO UITerms (UITermId, InternalName) VALUES(22, 'Description');
INSERT INTO UITerms (UITermId, InternalName) VALUES(23, 'Drop down name');
INSERT INTO UITerms (UITermId, InternalName) VALUES(24, 'Edit');
INSERT INTO UITerms (UITermId, InternalName) VALUES(25, 'Edit classification');
INSERT INTO UITerms (UITermId, InternalName) VALUES(26, 'Edit classification level');
INSERT INTO UITerms (UITermId, InternalName) VALUES(27, 'Edit language');
INSERT INTO UITerms (UITermId, InternalName) VALUES(28, 'Edit value');
INSERT INTO UITerms (UITermId, InternalName) VALUES(29, 'Has dropdown');
INSERT INTO UITerms (UITermId, InternalName) VALUES(30, 'Header description');
INSERT INTO UITerms (UITermId, InternalName) VALUES(31, 'Header name');
INSERT INTO UITerms (UITermId, InternalName) VALUES(32, 'In drop down');
INSERT INTO UITerms (UITermId, InternalName) VALUES(33, 'Language');
INSERT INTO UITerms (UITermId, InternalName) VALUES(34, 'Languages');
INSERT INTO UITerms (UITermId, InternalName) VALUES(35, 'Logout');
INSERT INTO UITerms (UITermId, InternalName) VALUES(36, 'Menu name');
INSERT INTO UITerms (UITermId, InternalName) VALUES(37, 'Mouse over');
INSERT INTO UITerms (UITermId, InternalName) VALUES(38, 'New value');
INSERT INTO UITerms (UITermId, InternalName) VALUES(39, 'On the fly');
INSERT INTO UITerms (UITermId, InternalName) VALUES(40, 'Open');
INSERT INTO UITerms (UITermId, InternalName) VALUES(41, 'Organization');
INSERT INTO UITerms (UITermId, InternalName) VALUES(42, 'Organization type');
INSERT INTO UITerms (UITermId, InternalName) VALUES(43, 'Page description');
INSERT INTO UITerms (UITermId, InternalName) VALUES(44, 'Page name');
INSERT INTO UITerms (UITermId, InternalName) VALUES(45, 'Page type');
INSERT INTO UITerms (UITermId, InternalName) VALUES(46, 'Pages');
INSERT INTO UITerms (UITermId, InternalName) VALUES(47, 'Process template field types');
INSERT INTO UITerms (UITermId, InternalName) VALUES(48, 'Process template groups');
INSERT INTO UITerms (UITermId, InternalName) VALUES(49, 'Process templates');
INSERT INTO UITerms (UITermId, InternalName) VALUES(50, 'Projects');
INSERT INTO UITerms (UITermId, InternalName) VALUES(51, 'Roles');
INSERT INTO UITerms (UITermId, InternalName) VALUES(52, 'Save');
INSERT INTO UITerms (UITermId, InternalName) VALUES(53, 'Section types');
INSERT INTO UITerms (UITermId, InternalName) VALUES(54, 'Settings');
INSERT INTO UITerms (UITermId, InternalName) VALUES(55, 'Setup wizard');
INSERT INTO UITerms (UITermId, InternalName) VALUES(56, 'Status');
INSERT INTO UITerms (UITermId, InternalName) VALUES(57, 'Terms');
INSERT INTO UITerms (UITermId, InternalName) VALUES(58, 'Topic name');
INSERT INTO UITerms (UITermId, InternalName) VALUES(59, 'Classifications');
INSERT INTO UITerms (UITermId, InternalName) VALUES(60, 'Levels');
INSERT INTO UITerms (UITermId, InternalName) VALUES(61, 'Sequence');
INSERT INTO UITerms (UITermId, InternalName) VALUES(62, 'Classification level languages');
INSERT INTO UITerms (UITermId, InternalName) VALUES(63, 'Update');
INSERT INTO UITerms (UITermId, InternalName) VALUES(64, 'Users');
INSERT INTO UITerms (UITermId, InternalName) VALUES(65, 'Values');
INSERT INTO UITerms (UITermId, InternalName) VALUES(66, 'Delete classification');
INSERT INTO UITerms (UITermId, InternalName) VALUES(67, 'Creator');
INSERT INTO UITerms (UITermId, InternalName) VALUES(68, 'Modifier');
INSERT INTO UITerms (UITermId, InternalName) VALUES(69, 'Content types');
INSERT INTO UITerms (UITermId, InternalName) VALUES(70, 'Create new content type');
INSERT INTO UITerms (UITermId, InternalName) VALUES(71, 'Edit content type');
INSERT INTO UITerms (UITermId, InternalName) VALUES(72, 'Content type languages');
INSERT INTO UITerms (UITermId, InternalName) VALUES(73, 'Back to content types');
INSERT INTO UITerms (UITermId, InternalName) VALUES(74, 'Delete language');
INSERT INTO UITerms (UITermId, InternalName) VALUES(75, 'Organizations');
INSERT INTO UITerms (UITermId, InternalName) VALUES(76, 'Create new organization');
INSERT INTO UITerms (UITermId, InternalName) VALUES(77, 'Organization languages');
INSERT INTO UITerms (UITermId, InternalName) VALUES(78, 'Back to organization');
INSERT INTO UITerms (UITermId, InternalName) VALUES(79, 'Type');
INSERT INTO UITerms (UITermId, InternalName) VALUES(80, 'Parent organization');
INSERT INTO UITerms (UITermId, InternalName) VALUES(81, 'Organization types');
INSERT INTO UITerms (UITermId, InternalName) VALUES(82, 'Create new organization type');
INSERT INTO UITerms (UITermId, InternalName) VALUES(83, 'Edit organization type');
INSERT INTO UITerms (UITermId, InternalName) VALUES(84, 'Organization type languages');
INSERT INTO UITerms (UITermId, InternalName) VALUES(85, 'Back to organization types');
INSERT INTO UITerms (UITermId, InternalName) VALUES(86, 'Sections');
INSERT INTO UITerms (UITermId, InternalName) VALUES(87, 'Create page');
INSERT INTO UITerms (UITermId, InternalName) VALUES(88, 'Edit page');
INSERT INTO UITerms (UITermId, InternalName) VALUES(89, 'Page sections');
INSERT INTO UITerms (UITermId, InternalName) VALUES(90, 'Create new page section');
INSERT INTO UITerms (UITermId, InternalName) VALUES(91, 'Back to pages');
INSERT INTO UITerms (UITermId, InternalName) VALUES(92, 'Edit page section');
INSERT INTO UITerms (UITermId, InternalName) VALUES(93, 'Back to page sections');
INSERT INTO UITerms (UITermId, InternalName) VALUES(94, 'Create page section');
INSERT INTO UITerms (UITermId, InternalName) VALUES(95, 'Title');
INSERT INTO UITerms (UITermId, InternalName) VALUES(96, 'Show title');
INSERT INTO UITerms (UITermId, InternalName) VALUES(97, 'Show title description');
INSERT INTO UITerms (UITermId, InternalName) VALUES(98, 'Show content type title');
INSERT INTO UITerms (UITermId, InternalName) VALUES(99, 'Show content type description');
INSERT INTO UITerms (UITermId, InternalName) VALUES(100, 'Page types');
INSERT INTO UITerms (UITermId, InternalName) VALUES(101, 'Create new page type');
INSERT INTO UITerms (UITermId, InternalName) VALUES(102, 'Edit page type');
INSERT INTO UITerms (UITermId, InternalName) VALUES(103, 'Page type languages');
INSERT INTO UITerms (UITermId, InternalName) VALUES(104, 'Back to page types');
INSERT INTO UITerms (UITermId, InternalName) VALUES(105, 'Create new project');
INSERT INTO UITerms (UITermId, InternalName) VALUES(106, 'Edit project');
INSERT INTO UITerms (UITermId, InternalName) VALUES(107, 'Project languages');
INSERT INTO UITerms (UITermId, InternalName) VALUES(108, 'Back to projects');
INSERT INTO UITerms (UITermId, InternalName) VALUES(109, 'Page section types');
INSERT INTO UITerms (UITermId, InternalName) VALUES(110, 'Create new page section type');
INSERT INTO UITerms (UITermId, InternalName) VALUES(111, 'Edit page section type');
INSERT INTO UITerms (UITermId, InternalName) VALUES(112, 'Index section');
INSERT INTO UITerms (UITermId, InternalName) VALUES(113, 'Page section type languages');
INSERT INTO UITerms (UITermId, InternalName) VALUES(114, 'Back to page section types');
INSERT INTO UITerms (UITermId, InternalName) VALUES(115, 'Relations');
INSERT INTO UITerms (UITermId, InternalName) VALUES(116, 'Add new role');
INSERT INTO UITerms (UITermId, InternalName) VALUES(117, 'Edit user');
INSERT INTO UITerms (UITermId, InternalName) VALUES(118, 'Create user');
INSERT INTO UITerms (UITermId, InternalName) VALUES(119, 'Email');
INSERT INTO UITerms (UITermId, InternalName) VALUES(120, 'Default language');
INSERT INTO UITerms (UITermId, InternalName) VALUES(121, 'Country');
INSERT INTO UITerms (UITermId, InternalName) VALUES(122, 'Password');
INSERT INTO UITerms (UITermId, InternalName) VALUES(123, 'Confirm password');
INSERT INTO UITerms (UITermId, InternalName) VALUES(124, 'User projects');
INSERT INTO UITerms (UITermId, InternalName) VALUES(125, 'Back to users');
INSERT INTO UITerms (UITermId, InternalName) VALUES(126, 'Add user to project');
INSERT INTO UITerms (UITermId, InternalName) VALUES(127, 'Project');
INSERT INTO UITerms (UITermId, InternalName) VALUES(128, 'Edit role');
INSERT INTO UITerms (UITermId, InternalName) VALUES(129, 'Manage users');
INSERT INTO UITerms (UITermId, InternalName) VALUES(130, 'Rights');
INSERT INTO UITerms (UITermId, InternalName) VALUES(131, 'Manage rights');
INSERT INTO UITerms (UITermId, InternalName) VALUES(132, 'Manage users to role');
INSERT INTO UITerms (UITermId, InternalName) VALUES(133, 'Role Id');
INSERT INTO UITerms (UITermId, InternalName) VALUES(134, 'User name');
INSERT INTO UITerms (UITermId, InternalName) VALUES(135, 'Manage rights to role');
INSERT INTO UITerms (UITermId, InternalName) VALUES(136, 'Selected');
INSERT INTO UITerms (UITermId, InternalName) VALUES(137, 'Claim type');
INSERT INTO UITerms (UITermId, InternalName) VALUES(138, 'Claim value');
INSERT INTO UITerms (UITermId, InternalName) VALUES(139, 'Role');
INSERT INTO UITerms (UITermId, InternalName) VALUES(140, 'Create new role');
INSERT INTO UITerms (UITermId, InternalName) VALUES(141, 'Role name');
INSERT INTO UITerms (UITermId, InternalName) VALUES(142, 'Fields');
INSERT INTO UITerms (UITermId, InternalName) VALUES(143, 'Flow');
INSERT INTO UITerms (UITermId, InternalName) VALUES(144, 'Edit process template');
INSERT INTO UITerms (UITermId, InternalName) VALUES(145, 'Create new process template');
INSERT INTO UITerms (UITermId, InternalName) VALUES(146, 'Process template group');
INSERT INTO UITerms (UITermId, InternalName) VALUES(147, 'Process template fields');
INSERT INTO UITerms (UITermId, InternalName) VALUES(148, 'Steps');
INSERT INTO UITerms (UITermId, InternalName) VALUES(149, 'Create new process template field');
INSERT INTO UITerms (UITermId, InternalName) VALUES(150, 'Edit process template field');
INSERT INTO UITerms (UITermId, InternalName) VALUES(151, 'Data type');
INSERT INTO UITerms (UITermId, InternalName) VALUES(152, 'Linked table');
INSERT INTO UITerms (UITermId, InternalName) VALUES(153, 'Steps for field');
INSERT INTO UITerms (UITermId, InternalName) VALUES(154, 'Edit step field settings');
INSERT INTO UITerms (UITermId, InternalName) VALUES(155, 'Process template field languages');
INSERT INTO UITerms (UITermId, InternalName) VALUES(156, 'Back to process template fields');
INSERT INTO UITerms (UITermId, InternalName) VALUES(157, 'Process template flows');
INSERT INTO UITerms (UITermId, InternalName) VALUES(158, 'Conditions');
INSERT INTO UITerms (UITermId, InternalName) VALUES(159, 'Create new process template flow');
INSERT INTO UITerms (UITermId, InternalName) VALUES(160, 'Back to process templates');
INSERT INTO UITerms (UITermId, InternalName) VALUES(161, 'Edit process template flow');
INSERT INTO UITerms (UITermId, InternalName) VALUES(162, 'Condition relation');
INSERT INTO UITerms (UITermId, InternalName) VALUES(163, 'From step');
INSERT INTO UITerms (UITermId, InternalName) VALUES(164, 'To step');
INSERT INTO UITerms (UITermId, InternalName) VALUES(165, 'Process template flow languages');
INSERT INTO UITerms (UITermId, InternalName) VALUES(166, 'Flow conditions');
INSERT INTO UITerms (UITermId, InternalName) VALUES(167, 'Char');
INSERT INTO UITerms (UITermId, InternalName) VALUES(168, 'Create new process template flow condition');
INSERT INTO UITerms (UITermId, InternalName) VALUES(169, 'Back to process template flows');
INSERT INTO UITerms (UITermId, InternalName) VALUES(170, 'Create new process template group');
INSERT INTO UITerms (UITermId, InternalName) VALUES(171, 'Edit process template group');
INSERT INTO UITerms (UITermId, InternalName) VALUES(172, 'Process template group languages');
INSERT INTO UITerms (UITermId, InternalName) VALUES(173, 'Back to process template groups');
INSERT INTO UITerms (UITermId, InternalName) VALUES(174, 'Create content');
INSERT INTO UITerms (UITermId, InternalName) VALUES(175, 'Content title');
INSERT INTO UITerms (UITermId, InternalName) VALUES(176, 'Content description');
INSERT INTO UITerms (UITermId, InternalName) VALUES(177, 'Content status');
INSERT INTO UITerms (UITermId, InternalName) VALUES(178, 'Content organization');
INSERT INTO UITerms (UITermId, InternalName) VALUES(179, 'Content project');
INSERT INTO UITerms (UITermId, InternalName) VALUES(180, 'Foreign name');
INSERT INTO UITerms (UITermId, InternalName) VALUES(181, 'ISO6391');
INSERT INTO UITerms (UITermId, InternalName) VALUES(182, 'ISO6392');
INSERT INTO UITerms (UITermId, InternalName) VALUES(183, 'Back to process fields');
INSERT INTO UITerms (UITermId, InternalName) VALUES(184, 'Fields for step');
INSERT INTO UITerms (UITermId, InternalName) VALUES(185, 'Back to steps');
INSERT INTO UITerms (UITermId, InternalName) VALUES(186, 'Process template steps');
INSERT INTO UITerms (UITermId, InternalName) VALUES(187, 'Create new process template step');
INSERT INTO UITerms (UITermId, InternalName) VALUES(188, 'Edit step');
INSERT INTO UITerms (UITermId, InternalName) VALUES(189, 'Add step');
INSERT INTO UITerms (UITermId, InternalName) VALUES(190, 'Process template step languages');
INSERT INTO UITerms (UITermId, InternalName) VALUES(191, 'Add new language');
INSERT INTO UITerms (UITermId, InternalName) VALUES(192, 'Active');
INSERT INTO UITerms (UITermId, InternalName) VALUES(193, 'Int');
INSERT INTO UITerms (UITermId, InternalName) VALUES(194, 'String');
INSERT INTO UITerms (UITermId, InternalName) VALUES(195, 'Date');
INSERT INTO UITerms (UITermId, InternalName) VALUES(196, 'Edit setting');
INSERT INTO UITerms (UITermId, InternalName) VALUES(197, 'Process template field type languages');
INSERT INTO UITerms (UITermId, InternalName) VALUES(198, 'Edit process template field type');
INSERT INTO UITerms (UITermId, InternalName) VALUES(199, 'Delete process template field type');
INSERT INTO UITerms (UITermId, InternalName) VALUES(200, 'Create process template field type');
INSERT INTO UITerms (UITermId, InternalName) VALUES(201, 'Back to process template field types');
INSERT INTO UITerms (UITermId, InternalName) VALUES(202, 'User organization type');
INSERT INTO UITerms (UITermId, InternalName) VALUES(203, 'User organization type languages');
INSERT INTO UITerms (UITermId, InternalName) VALUES(204, 'Add user organization type language');
INSERT INTO UITerms (UITermId, InternalName) VALUES(205, 'Back to user organization types');
INSERT INTO UITerms (UITermId, InternalName) VALUES(206, 'CreatedDate');
INSERT INTO UITerms (UITermId, InternalName) VALUES(207, 'ModifiedDate');
INSERT INTO UITerms (UITermId, InternalName) VALUES(208, 'Delete content type');
INSERT INTO UITerms (UITermId, InternalName) VALUES(209, 'Delete organization');
INSERT INTO UITerms (UITermId, InternalName) VALUES(210, 'Delete organization type');
INSERT INTO UITerms (UITermId, InternalName) VALUES(211, 'Delete page');
INSERT INTO UITerms (UITermId, InternalName) VALUES(212, 'Delete page section');
INSERT INTO UITerms (UITermId, InternalName) VALUES(213, 'Has paging');
INSERT INTO UITerms (UITermId, InternalName) VALUES(214, 'Max content');
INSERT INTO UITerms (UITermId, InternalName) VALUES(215, 'One two columns');
INSERT INTO UITerms (UITermId, InternalName) VALUES(216, 'Page section languages');
INSERT INTO UITerms (UITermId, InternalName) VALUES(217, 'Page languages');
INSERT INTO UITerms (UITermId, InternalName) VALUES(218, 'Application title');
INSERT INTO UITerms (UITermId, InternalName) VALUES(219, 'Drop down sequence');
INSERT INTO UITerms (UITermId, InternalName) VALUES(220, 'Default page');
INSERT INTO UITerms (UITermId, InternalName) VALUES(221, 'Preference');
INSERT INTO UITerms (UITermId, InternalName) VALUES(222, 'User project type');
INSERT INTO UITerms (UITermId, InternalName) VALUES(223, 'User relation type');
INSERT INTO UITerms (UITermId, InternalName) VALUES(224, 'login');
INSERT INTO UITerms (UITermId, InternalName) VALUES(225, 'Register');
INSERT INTO UITerms (UITermId, InternalName) VALUES(226, 'Add content');
INSERT INTO UITerms (UITermId, InternalName) VALUES(227, 'Content');
INSERT INTO UITerms (UITermId, InternalName) VALUES(228, 'Calendar');
INSERT INTO UITerms (UITermId, InternalName) VALUES(229, 'Chat');
INSERT INTO UITerms (UITermId, InternalName) VALUES(230, 'Conference');
INSERT INTO UITerms (UITermId, InternalName) VALUES(231, 'Favorites');
INSERT INTO UITerms (UITermId, InternalName) VALUES(232, 'Game');
INSERT INTO UITerms (UITermId, InternalName) VALUES(233, 'Add process');
INSERT INTO UITerms (UITermId, InternalName) VALUES(234, 'Process');
INSERT INTO UITerms (UITermId, InternalName) VALUES(235, 'Add todo');
INSERT INTO UITerms (UITermId, InternalName) VALUES(236, 'Todo');
INSERT INTO UITerms (UITermId, InternalName) VALUES(237, 'Search');
INSERT INTO UITerms (UITermId, InternalName) VALUES(238, 'Classification pages');
INSERT INTO UITerms (UITermId, InternalName) VALUES(239, 'Create new classification page');
INSERT INTO UITerms (UITermId, InternalName) VALUES(240, 'Edit classification page');
INSERT INTO UITerms (UITermId, InternalName) VALUES(241, 'Show title name');
INSERT INTO UITerms (UITermId, InternalName) VALUES(242, 'Title name');
INSERT INTO UITerms (UITermId, InternalName) VALUES(243, 'Delete classification page');
INSERT INTO UITerms (UITermId, InternalName) VALUES(244, 'Back to classification pages');
INSERT INTO UITerms (UITermId, InternalName) VALUES(245, 'Classification page sections');
INSERT INTO UITerms (UITermId, InternalName) VALUES(246, 'Create new classification page section');
INSERT INTO UITerms (UITermId, InternalName) VALUES(247, 'Edit classification page section');
INSERT INTO UITerms (UITermId, InternalName) VALUES(248, 'Section type');
INSERT INTO UITerms (UITermId, InternalName) VALUES(249, 'Show section title name');
INSERT INTO UITerms (UITermId, InternalName) VALUES(250, 'Show section title description');
INSERT INTO UITerms (UITermId, InternalName) VALUES(251, 'Show content type title name');
INSERT INTO UITerms (UITermId, InternalName) VALUES(252, 'Show content type title description');
INSERT INTO UITerms (UITermId, InternalName) VALUES(253, 'Sort by');
INSERT INTO UITerms (UITermId, InternalName) VALUES(254, 'Delete classification page section');
INSERT INTO UITerms (UITermId, InternalName) VALUES(255, 'In Menu');
INSERT INTO UITerms (UITermId, InternalName) VALUES(256, 'User Project type languages');
INSERT INTO UITerms (UITermId, InternalName) VALUES(257, 'Add user Project type language');
INSERT INTO UITerms (UITermId, InternalName) VALUES(258, 'Back to user Project types');
INSERT INTO UITerms (UITermId, InternalName) VALUES(259, 'From is of to name');
INSERT INTO UITerms (UITermId, InternalName) VALUES(260, 'To is of from name');
INSERT INTO UITerms (UITermId, InternalName) VALUES(261, 'From is of to description');
INSERT INTO UITerms (UITermId, InternalName) VALUES(262, 'To is of from description');
INSERT INTO UITerms (UITermId, InternalName) VALUES(263, 'From is of to mouse over');
INSERT INTO UITerms (UITermId, InternalName) VALUES(264, 'To is of from mouse over');
INSERT INTO UITerms (UITermId, InternalName) VALUES(265, 'From is of to menu name');
INSERT INTO UITerms (UITermId, InternalName) VALUES(266, 'To is of from menu name');
INSERT INTO UITerms (UITermId, InternalName) VALUES(267, 'Back to user relation types');
INSERT INTO UITerms (UITermId, InternalName) VALUES(268, 'Add user relation type language');
INSERT INTO UITerms (UITermId, InternalName) VALUES(269, 'User relation types');
INSERT INTO UITerms (UITermId, InternalName) VALUES(270, 'Edit user relation type language');
INSERT INTO UITerms (UITermId, InternalName) VALUES(271, 'Delete user relation type language');
INSERT INTO UITerms (UITermId, InternalName) VALUES(272, 'To do');
INSERT INTO UITerms (UITermId, InternalName) VALUES(273, 'Process name');
INSERT INTO UITerms (UITermId, InternalName) VALUES(274, 'Add menu');
INSERT INTO UITerms (UITermId, InternalName) VALUES(275, 'Controller');
INSERT INTO UITerms (UITermId, InternalName) VALUES(276, 'Action');
INSERT INTO UITerms (UITermId, InternalName) VALUES(277, 'Destination Id');
INSERT INTO UITerms (UITermId, InternalName) VALUES(278, 'Feature');
INSERT INTO UITerms (UITermId, InternalName) VALUES(279, 'Delete menu');
INSERT INTO UITerms (UITermId, InternalName) VALUES(280, 'OId');
INSERT INTO UITerms (UITermId, InternalName) VALUES(281, 'Type name');
INSERT INTO UITerms (UITermId, InternalName) VALUES(282, 'LId');
INSERT INTO UITerms (UITermId, InternalName) VALUES(283, 'Edit menu');
INSERT INTO UITerms (UITermId, InternalName) VALUES(284, 'Menu type');
INSERT INTO UITerms (UITermId, InternalName) VALUES(285, 'Menus');
INSERT INTO UITerms (UITermId, InternalName) VALUES(286, 'Menu level 2');
INSERT INTO UITerms (UITermId, InternalName) VALUES(287, 'Back to menu');
INSERT INTO UITerms (UITermId, InternalName) VALUES(288, 'Left menu');
INSERT INTO UITerms (UITermId, InternalName) VALUES(289, 'Edit left menu');
INSERT INTO UITerms (UITermId, InternalName) VALUES(290, 'Menu');
INSERT INTO UITerms (UITermId, InternalName) VALUES(291, 'Menu description');
INSERT INTO UITerms (UITermId, InternalName) VALUES(292, 'Show menu');
INSERT INTO UITerms (UITermId, InternalName) VALUES(293, 'Show add menu');
INSERT INTO UITerms (UITermId, InternalName) VALUES(294, 'Show search');
INSERT INTO UITerms (UITermId, InternalName) VALUES(295, 'Show advanced search');
INSERT INTO UITerms (UITermId, InternalName) VALUES(296, 'Menu URL');
INSERT INTO UITerms (UITermId, InternalName) VALUES(297, 'Parent project');
INSERT INTO UITerms (UITermId, InternalName) VALUES(298, 'Create new user');
INSERT INTO UITerms (UITermId, InternalName) VALUES(299, 'Relation');
INSERT INTO UITerms (UITermId, InternalName) VALUES(300, 'TRUE');
INSERT INTO UITerms (UITermId, InternalName) VALUES(301, 'FALSE');
INSERT INTO UITerms (UITermId, InternalName) VALUES(302, 'Build data');
INSERT INTO UITerms (UITermId, InternalName) VALUES(303, 'Master data');
INSERT INTO UITerms (UITermId, InternalName) VALUES(304, 'Login as eplegrand@gmail.com');
INSERT INTO UITerms (UITermId, InternalName) VALUES(305, 'Demo data');
INSERT INTO UITerms (UITermId, InternalName) VALUES(306, 'Demo data NL');
INSERT INTO UITerms (UITermId, InternalName) VALUES(307, 'Demo data is done');
INSERT INTO UITerms (UITermId, InternalName) VALUES(308, 'Back to Setup wizard');
INSERT INTO UITerms (UITermId, InternalName) VALUES(309, 'View content');
INSERT INTO UITerms (UITermId, InternalName) VALUES(310, 'Content type classifications');
INSERT INTO UITerms (UITermId, InternalName) VALUES(311, 'Edit content type classification');
INSERT INTO UITerms (UITermId, InternalName) VALUES(312, 'Security level');
INSERT INTO UITerms (UITermId, InternalName) VALUES(313, 'Created flow');
INSERT INTO UITerms (UITermId, InternalName) VALUES(314, 'Add left menu');
INSERT INTO UITerms (UITermId, InternalName) VALUES(315, 'New menu');
INSERT INTO UITerms (UITermId, InternalName) VALUES(316, 'Location');
INSERT INTO UITerms (UITermId, InternalName) VALUES(317, 'User dashboard');
INSERT INTO UITerms (UITermId, InternalName) VALUES(318, 'User');
INSERT INTO UITerms (UITermId, InternalName) VALUES(319, 'Content type group');
INSERT INTO UITerms (UITermId, InternalName) VALUES(320, 'Process template');
INSERT INTO UITerms (UITermId, InternalName) VALUES(321, 'Primary address');
INSERT INTO UITerms (UITermId, InternalName) VALUES(322, 'Delivery address');
INSERT INTO UITerms (UITermId, InternalName) VALUES(323, 'Billing address');
INSERT INTO UITerms (UITermId, InternalName) VALUES(324, 'At least all people and organizations should have a primary address');
INSERT INTO UITerms (UITermId, InternalName) VALUES(325, 'The delivery address is used to receive letters and packages');
INSERT INTO UITerms (UITermId, InternalName) VALUES(326, 'The billing address is used for receiving invoices');
INSERT INTO UITerms (UITermId, InternalName) VALUES(327, 'Inactive');
INSERT INTO UITerms (UITermId, InternalName) VALUES(328, 'No date');
INSERT INTO UITerms (UITermId, InternalName) VALUES(329, 'Single date');
INSERT INTO UITerms (UITermId, InternalName) VALUES(330, 'Date range');
INSERT INTO UITerms (UITermId, InternalName) VALUES(331, 'Single date time');
INSERT INTO UITerms (UITermId, InternalName) VALUES(332, 'Date time range');
INSERT INTO UITerms (UITermId, InternalName) VALUES(333, 'List');
INSERT INTO UITerms (UITermId, InternalName) VALUES(334, 'Index');
INSERT INTO UITerms (UITermId, InternalName) VALUES(335, 'Draft');
INSERT INTO UITerms (UITermId, InternalName) VALUES(336, 'Pending');
INSERT INTO UITerms (UITermId, InternalName) VALUES(337, 'Rejected');
INSERT INTO UITerms (UITermId, InternalName) VALUES(338, 'Approved');
INSERT INTO UITerms (UITermId, InternalName) VALUES(339, 'Hidden');
INSERT INTO UITerms (UITermId, InternalName) VALUES(340, 'Optional');
INSERT INTO UITerms (UITermId, InternalName) VALUES(341, 'Required');
INSERT INTO UITerms (UITermId, InternalName) VALUES(342, 'Newest');
INSERT INTO UITerms (UITermId, InternalName) VALUES(343, 'Most popular');
INSERT INTO UITerms (UITermId, InternalName) VALUES(344, 'Europe');
INSERT INTO UITerms (UITermId, InternalName) VALUES(345, 'Americas');
INSERT INTO UITerms (UITermId, InternalName) VALUES(346, 'Oceania');
INSERT INTO UITerms (UITermId, InternalName) VALUES(347, 'Asia');
INSERT INTO UITerms (UITermId, InternalName) VALUES(348, 'Africa');
INSERT INTO UITerms (UITermId, InternalName) VALUES(349, 'Australia and New Zealand');
INSERT INTO UITerms (UITermId, InternalName) VALUES(350, 'Southern Europe');
INSERT INTO UITerms (UITermId, InternalName) VALUES(351, 'Southern Asia');
INSERT INTO UITerms (UITermId, InternalName) VALUES(352, 'Western Europe');
INSERT INTO UITerms (UITermId, InternalName) VALUES(353, 'Eastern Asia');
INSERT INTO UITerms (UITermId, InternalName) VALUES(354, 'Eastern Europe');
INSERT INTO UITerms (UITermId, InternalName) VALUES(355, 'Northern Europe');
INSERT INTO UITerms (UITermId, InternalName) VALUES(356, 'Northern America');
INSERT INTO UITerms (UITermId, InternalName) VALUES(357, 'Micronesia');
INSERT INTO UITerms (UITermId, InternalName) VALUES(358, 'Central Asia');
INSERT INTO UITerms (UITermId, InternalName) VALUES(359, 'Melanesia');
INSERT INTO UITerms (UITermId, InternalName) VALUES(360, 'South-eastern Asia');
INSERT INTO UITerms (UITermId, InternalName) VALUES(361, 'Latin America and the Caribbean');
INSERT INTO UITerms (UITermId, InternalName) VALUES(362, 'Polynesia');
INSERT INTO UITerms (UITermId, InternalName) VALUES(363, 'Northern Africa');
INSERT INTO UITerms (UITermId, InternalName) VALUES(364, 'Western Asia');
INSERT INTO UITerms (UITermId, InternalName) VALUES(365, 'Sub-Saharan Africa');
INSERT INTO UITerms (UITermId, InternalName) VALUES(366, 'Channel Islands');
INSERT INTO UITerms (UITermId, InternalName) VALUES(367, 'Central America');
INSERT INTO UITerms (UITermId, InternalName) VALUES(368, 'Middle Africa');
INSERT INTO UITerms (UITermId, InternalName) VALUES(369, 'Southern Africa');
INSERT INTO UITerms (UITermId, InternalName) VALUES(370, 'Western Africa');
INSERT INTO UITerms (UITermId, InternalName) VALUES(371, 'South America');
INSERT INTO UITerms (UITermId, InternalName) VALUES(372, 'Caribbean');
INSERT INTO UITerms (UITermId, InternalName) VALUES(373, 'Eastern Africa');
INSERT INTO UITerms (UITermId, InternalName) VALUES(374, 'Afghanistan');
INSERT INTO UITerms (UITermId, InternalName) VALUES(375, 'Åland Islands');
INSERT INTO UITerms (UITermId, InternalName) VALUES(376, 'Albania');
INSERT INTO UITerms (UITermId, InternalName) VALUES(377, 'Algeria');
INSERT INTO UITerms (UITermId, InternalName) VALUES(378, 'American Samoa');
INSERT INTO UITerms (UITermId, InternalName) VALUES(379, 'Andorra');
INSERT INTO UITerms (UITermId, InternalName) VALUES(380, 'Angola');
INSERT INTO UITerms (UITermId, InternalName) VALUES(381, 'Anguilla');
INSERT INTO UITerms (UITermId, InternalName) VALUES(382, 'Antarctica');
INSERT INTO UITerms (UITermId, InternalName) VALUES(383, 'Antigua and Barbuda');
INSERT INTO UITerms (UITermId, InternalName) VALUES(384, 'Argentina');
INSERT INTO UITerms (UITermId, InternalName) VALUES(385, 'Armenia');
INSERT INTO UITerms (UITermId, InternalName) VALUES(386, 'Aruba');
INSERT INTO UITerms (UITermId, InternalName) VALUES(387, 'Australia');
INSERT INTO UITerms (UITermId, InternalName) VALUES(388, 'Austria');
INSERT INTO UITerms (UITermId, InternalName) VALUES(389, 'Azerbaijan');
INSERT INTO UITerms (UITermId, InternalName) VALUES(390, 'Bahamas');
INSERT INTO UITerms (UITermId, InternalName) VALUES(391, 'Bahrain');
INSERT INTO UITerms (UITermId, InternalName) VALUES(392, 'Bangladesh');
INSERT INTO UITerms (UITermId, InternalName) VALUES(393, 'Barbados');
INSERT INTO UITerms (UITermId, InternalName) VALUES(394, 'Belarus');
INSERT INTO UITerms (UITermId, InternalName) VALUES(395, 'Belgium');
INSERT INTO UITerms (UITermId, InternalName) VALUES(396, 'Belize');
INSERT INTO UITerms (UITermId, InternalName) VALUES(397, 'Benin');
INSERT INTO UITerms (UITermId, InternalName) VALUES(398, 'Bermuda');
INSERT INTO UITerms (UITermId, InternalName) VALUES(399, 'Bhutan');
INSERT INTO UITerms (UITermId, InternalName) VALUES(400, 'Bolivia (Plurinational State of)');
INSERT INTO UITerms (UITermId, InternalName) VALUES(401, 'Bonaire, Sint Eustatius and Saba');
INSERT INTO UITerms (UITermId, InternalName) VALUES(402, 'Bosnia and Herzegovina');
INSERT INTO UITerms (UITermId, InternalName) VALUES(403, 'Botswana');
INSERT INTO UITerms (UITermId, InternalName) VALUES(404, 'Bouvet Island');
INSERT INTO UITerms (UITermId, InternalName) VALUES(405, 'Brazil');
INSERT INTO UITerms (UITermId, InternalName) VALUES(406, 'British Indian Ocean Territory');
INSERT INTO UITerms (UITermId, InternalName) VALUES(407, 'Brunei Darussalam');
INSERT INTO UITerms (UITermId, InternalName) VALUES(408, 'Bulgaria');
INSERT INTO UITerms (UITermId, InternalName) VALUES(409, 'Burkina Faso');
INSERT INTO UITerms (UITermId, InternalName) VALUES(410, 'Burundi');
INSERT INTO UITerms (UITermId, InternalName) VALUES(411, 'Cabo Verde');
INSERT INTO UITerms (UITermId, InternalName) VALUES(412, 'Cambodia');
INSERT INTO UITerms (UITermId, InternalName) VALUES(413, 'Cameroon');
INSERT INTO UITerms (UITermId, InternalName) VALUES(414, 'Canada');
INSERT INTO UITerms (UITermId, InternalName) VALUES(415, 'Cayman Islands');
INSERT INTO UITerms (UITermId, InternalName) VALUES(416, 'Central African Republic');
INSERT INTO UITerms (UITermId, InternalName) VALUES(417, 'Chad');
INSERT INTO UITerms (UITermId, InternalName) VALUES(418, 'Chile');
INSERT INTO UITerms (UITermId, InternalName) VALUES(419, 'China');
INSERT INTO UITerms (UITermId, InternalName) VALUES(420, 'Christmas Island');
INSERT INTO UITerms (UITermId, InternalName) VALUES(421, 'Cocos (Keeling) Islands');
INSERT INTO UITerms (UITermId, InternalName) VALUES(422, 'Colombia');
INSERT INTO UITerms (UITermId, InternalName) VALUES(423, 'Comoros');
INSERT INTO UITerms (UITermId, InternalName) VALUES(424, 'Congo');
INSERT INTO UITerms (UITermId, InternalName) VALUES(425, 'Congo, Democratic Republic of the');
INSERT INTO UITerms (UITermId, InternalName) VALUES(426, 'Cook Islands');
INSERT INTO UITerms (UITermId, InternalName) VALUES(427, 'Costa Rica');
INSERT INTO UITerms (UITermId, InternalName) VALUES(428, 'Côte d''Ivoire');
INSERT INTO UITerms (UITermId, InternalName) VALUES(429, 'Croatia');
INSERT INTO UITerms (UITermId, InternalName) VALUES(430, 'Cuba');
INSERT INTO UITerms (UITermId, InternalName) VALUES(431, 'Curaçao');
INSERT INTO UITerms (UITermId, InternalName) VALUES(432, 'Cyprus');
INSERT INTO UITerms (UITermId, InternalName) VALUES(433, 'Czechia');
INSERT INTO UITerms (UITermId, InternalName) VALUES(434, 'Denmark');
INSERT INTO UITerms (UITermId, InternalName) VALUES(435, 'Djibouti');
INSERT INTO UITerms (UITermId, InternalName) VALUES(436, 'Dominica');
INSERT INTO UITerms (UITermId, InternalName) VALUES(437, 'Dominican Republic');
INSERT INTO UITerms (UITermId, InternalName) VALUES(438, 'Ecuador');
INSERT INTO UITerms (UITermId, InternalName) VALUES(439, 'Egypt');
INSERT INTO UITerms (UITermId, InternalName) VALUES(440, 'El Salvador');
INSERT INTO UITerms (UITermId, InternalName) VALUES(441, 'Equatorial Guinea');
INSERT INTO UITerms (UITermId, InternalName) VALUES(442, 'Eritrea');
INSERT INTO UITerms (UITermId, InternalName) VALUES(443, 'Estonia');
INSERT INTO UITerms (UITermId, InternalName) VALUES(444, 'Eswatini');
INSERT INTO UITerms (UITermId, InternalName) VALUES(445, 'Ethiopia');
INSERT INTO UITerms (UITermId, InternalName) VALUES(446, 'Falkland Islands (Malvinas)');
INSERT INTO UITerms (UITermId, InternalName) VALUES(447, 'Faroe Islands');
INSERT INTO UITerms (UITermId, InternalName) VALUES(448, 'Fiji');
INSERT INTO UITerms (UITermId, InternalName) VALUES(449, 'Finland');
INSERT INTO UITerms (UITermId, InternalName) VALUES(450, 'France');
INSERT INTO UITerms (UITermId, InternalName) VALUES(451, 'French Guiana');
INSERT INTO UITerms (UITermId, InternalName) VALUES(452, 'French Polynesia');
INSERT INTO UITerms (UITermId, InternalName) VALUES(453, 'French Southern Territories');
INSERT INTO UITerms (UITermId, InternalName) VALUES(454, 'Gabon');
INSERT INTO UITerms (UITermId, InternalName) VALUES(455, 'Gambia');
INSERT INTO UITerms (UITermId, InternalName) VALUES(456, 'Georgia');
INSERT INTO UITerms (UITermId, InternalName) VALUES(457, 'Germany');
INSERT INTO UITerms (UITermId, InternalName) VALUES(458, 'Ghana');
INSERT INTO UITerms (UITermId, InternalName) VALUES(459, 'Gibraltar');
INSERT INTO UITerms (UITermId, InternalName) VALUES(460, 'Greece');
INSERT INTO UITerms (UITermId, InternalName) VALUES(461, 'Greenland');
INSERT INTO UITerms (UITermId, InternalName) VALUES(462, 'Grenada');
INSERT INTO UITerms (UITermId, InternalName) VALUES(463, 'Guadeloupe');
INSERT INTO UITerms (UITermId, InternalName) VALUES(464, 'Guam');
INSERT INTO UITerms (UITermId, InternalName) VALUES(465, 'Guatemala');
INSERT INTO UITerms (UITermId, InternalName) VALUES(466, 'Guernsey');
INSERT INTO UITerms (UITermId, InternalName) VALUES(467, 'Guinea');
INSERT INTO UITerms (UITermId, InternalName) VALUES(468, 'Guinea-Bissau');
INSERT INTO UITerms (UITermId, InternalName) VALUES(469, 'Guyana');
INSERT INTO UITerms (UITermId, InternalName) VALUES(470, 'Haiti');
INSERT INTO UITerms (UITermId, InternalName) VALUES(471, 'Heard Island and McDonald Islands');
INSERT INTO UITerms (UITermId, InternalName) VALUES(472, 'Holy See');
INSERT INTO UITerms (UITermId, InternalName) VALUES(473, 'Honduras');
INSERT INTO UITerms (UITermId, InternalName) VALUES(474, 'Hong Kong');
INSERT INTO UITerms (UITermId, InternalName) VALUES(475, 'Hungary');
INSERT INTO UITerms (UITermId, InternalName) VALUES(476, 'Iceland');
INSERT INTO UITerms (UITermId, InternalName) VALUES(477, 'India');
INSERT INTO UITerms (UITermId, InternalName) VALUES(478, 'Indonesia');
INSERT INTO UITerms (UITermId, InternalName) VALUES(479, 'Iran (Islamic Republic of)');
INSERT INTO UITerms (UITermId, InternalName) VALUES(480, 'Iraq');
INSERT INTO UITerms (UITermId, InternalName) VALUES(481, 'Ireland');
INSERT INTO UITerms (UITermId, InternalName) VALUES(482, 'Isle of Man');
INSERT INTO UITerms (UITermId, InternalName) VALUES(483, 'Israel');
INSERT INTO UITerms (UITermId, InternalName) VALUES(484, 'Italy');
INSERT INTO UITerms (UITermId, InternalName) VALUES(485, 'Jamaica');
INSERT INTO UITerms (UITermId, InternalName) VALUES(486, 'Japan');
INSERT INTO UITerms (UITermId, InternalName) VALUES(487, 'Jersey');
INSERT INTO UITerms (UITermId, InternalName) VALUES(488, 'Jordan');
INSERT INTO UITerms (UITermId, InternalName) VALUES(489, 'Kazakhstan');
INSERT INTO UITerms (UITermId, InternalName) VALUES(490, 'Kenya');
INSERT INTO UITerms (UITermId, InternalName) VALUES(491, 'Kiribati');
INSERT INTO UITerms (UITermId, InternalName) VALUES(492, 'Korea (Democratic People''s Republic of)');
INSERT INTO UITerms (UITermId, InternalName) VALUES(493, 'Korea, Republic of');
INSERT INTO UITerms (UITermId, InternalName) VALUES(494, 'Kuwait');
INSERT INTO UITerms (UITermId, InternalName) VALUES(495, 'Kyrgyzstan');
INSERT INTO UITerms (UITermId, InternalName) VALUES(496, 'Lao People''s Democratic Republic');
INSERT INTO UITerms (UITermId, InternalName) VALUES(497, 'Latvia');
INSERT INTO UITerms (UITermId, InternalName) VALUES(498, 'Lebanon');
INSERT INTO UITerms (UITermId, InternalName) VALUES(499, 'Lesotho');
INSERT INTO UITerms (UITermId, InternalName) VALUES(500, 'Liberia');
INSERT INTO UITerms (UITermId, InternalName) VALUES(501, 'Libya');
INSERT INTO UITerms (UITermId, InternalName) VALUES(502, 'Liechtenstein');
INSERT INTO UITerms (UITermId, InternalName) VALUES(503, 'Lithuania');
INSERT INTO UITerms (UITermId, InternalName) VALUES(504, 'Luxembourg');
INSERT INTO UITerms (UITermId, InternalName) VALUES(505, 'Macao');
INSERT INTO UITerms (UITermId, InternalName) VALUES(506, 'Madagascar');
INSERT INTO UITerms (UITermId, InternalName) VALUES(507, 'Malawi');
INSERT INTO UITerms (UITermId, InternalName) VALUES(508, 'Malaysia');
INSERT INTO UITerms (UITermId, InternalName) VALUES(509, 'Maldives');
INSERT INTO UITerms (UITermId, InternalName) VALUES(510, 'Mali');
INSERT INTO UITerms (UITermId, InternalName) VALUES(511, 'Malta');
INSERT INTO UITerms (UITermId, InternalName) VALUES(512, 'Marshall Islands');
INSERT INTO UITerms (UITermId, InternalName) VALUES(513, 'Martinique');
INSERT INTO UITerms (UITermId, InternalName) VALUES(514, 'Mauritania');
INSERT INTO UITerms (UITermId, InternalName) VALUES(515, 'Mauritius');
INSERT INTO UITerms (UITermId, InternalName) VALUES(516, 'Mayotte');
INSERT INTO UITerms (UITermId, InternalName) VALUES(517, 'Mexico');
INSERT INTO UITerms (UITermId, InternalName) VALUES(518, 'Micronesia (Federated States of)');
INSERT INTO UITerms (UITermId, InternalName) VALUES(519, 'Moldova, Republic of');
INSERT INTO UITerms (UITermId, InternalName) VALUES(520, 'Monaco');
INSERT INTO UITerms (UITermId, InternalName) VALUES(521, 'Mongolia');
INSERT INTO UITerms (UITermId, InternalName) VALUES(522, 'Montenegro');
INSERT INTO UITerms (UITermId, InternalName) VALUES(523, 'Montserrat');
INSERT INTO UITerms (UITermId, InternalName) VALUES(524, 'Morocco');
INSERT INTO UITerms (UITermId, InternalName) VALUES(525, 'Mozambique');
INSERT INTO UITerms (UITermId, InternalName) VALUES(526, 'Myanmar');
INSERT INTO UITerms (UITermId, InternalName) VALUES(527, 'Namibia');
INSERT INTO UITerms (UITermId, InternalName) VALUES(528, 'Nauru');
INSERT INTO UITerms (UITermId, InternalName) VALUES(529, 'Nepal');
INSERT INTO UITerms (UITermId, InternalName) VALUES(530, 'Netherlands');
INSERT INTO UITerms (UITermId, InternalName) VALUES(531, 'New Caledonia');
INSERT INTO UITerms (UITermId, InternalName) VALUES(532, 'New Zealand');
INSERT INTO UITerms (UITermId, InternalName) VALUES(533, 'Nicaragua');
INSERT INTO UITerms (UITermId, InternalName) VALUES(534, 'Niger');
INSERT INTO UITerms (UITermId, InternalName) VALUES(535, 'Nigeria');
INSERT INTO UITerms (UITermId, InternalName) VALUES(536, 'Niue');
INSERT INTO UITerms (UITermId, InternalName) VALUES(537, 'Norfolk Island');
INSERT INTO UITerms (UITermId, InternalName) VALUES(538, 'North Macedonia');
INSERT INTO UITerms (UITermId, InternalName) VALUES(539, 'Northern Mariana Islands');
INSERT INTO UITerms (UITermId, InternalName) VALUES(540, 'Norway');
INSERT INTO UITerms (UITermId, InternalName) VALUES(541, 'Oman');
INSERT INTO UITerms (UITermId, InternalName) VALUES(542, 'Pakistan');
INSERT INTO UITerms (UITermId, InternalName) VALUES(543, 'Palau');
INSERT INTO UITerms (UITermId, InternalName) VALUES(544, 'Palestine, State of');
INSERT INTO UITerms (UITermId, InternalName) VALUES(545, 'Panama');
INSERT INTO UITerms (UITermId, InternalName) VALUES(546, 'Papua New Guinea');
INSERT INTO UITerms (UITermId, InternalName) VALUES(547, 'Paraguay');
INSERT INTO UITerms (UITermId, InternalName) VALUES(548, 'Peru');
INSERT INTO UITerms (UITermId, InternalName) VALUES(549, 'Philippines');
INSERT INTO UITerms (UITermId, InternalName) VALUES(550, 'Pitcairn');
INSERT INTO UITerms (UITermId, InternalName) VALUES(551, 'Poland');
INSERT INTO UITerms (UITermId, InternalName) VALUES(552, 'Portugal');
INSERT INTO UITerms (UITermId, InternalName) VALUES(553, 'Puerto Rico');
INSERT INTO UITerms (UITermId, InternalName) VALUES(554, 'Qatar');
INSERT INTO UITerms (UITermId, InternalName) VALUES(555, 'Réunion');
INSERT INTO UITerms (UITermId, InternalName) VALUES(556, 'Romania');
INSERT INTO UITerms (UITermId, InternalName) VALUES(557, 'Russian Federation');
INSERT INTO UITerms (UITermId, InternalName) VALUES(558, 'Rwanda');
INSERT INTO UITerms (UITermId, InternalName) VALUES(559, 'Saint Barthélemy');
INSERT INTO UITerms (UITermId, InternalName) VALUES(560, 'Saint Helena, Ascension and Tristan da Cunha');
INSERT INTO UITerms (UITermId, InternalName) VALUES(561, 'Saint Kitts and Nevis');
INSERT INTO UITerms (UITermId, InternalName) VALUES(562, 'Saint Lucia');
INSERT INTO UITerms (UITermId, InternalName) VALUES(563, 'Saint Martin (French part)');
INSERT INTO UITerms (UITermId, InternalName) VALUES(564, 'Saint Pierre and Miquelon');
INSERT INTO UITerms (UITermId, InternalName) VALUES(565, 'Saint Vincent and the Grenadines');
INSERT INTO UITerms (UITermId, InternalName) VALUES(566, 'Samoa');
INSERT INTO UITerms (UITermId, InternalName) VALUES(567, 'San Marino');
INSERT INTO UITerms (UITermId, InternalName) VALUES(568, 'Sao Tome and Principe');
INSERT INTO UITerms (UITermId, InternalName) VALUES(569, 'Saudi Arabia');
INSERT INTO UITerms (UITermId, InternalName) VALUES(570, 'Senegal');
INSERT INTO UITerms (UITermId, InternalName) VALUES(571, 'Serbia');
INSERT INTO UITerms (UITermId, InternalName) VALUES(572, 'Seychelles');
INSERT INTO UITerms (UITermId, InternalName) VALUES(573, 'Sierra Leone');
INSERT INTO UITerms (UITermId, InternalName) VALUES(574, 'Singapore');
INSERT INTO UITerms (UITermId, InternalName) VALUES(575, 'Sint Maarten (Dutch part)');
INSERT INTO UITerms (UITermId, InternalName) VALUES(576, 'Slovakia');
INSERT INTO UITerms (UITermId, InternalName) VALUES(577, 'Slovenia');
INSERT INTO UITerms (UITermId, InternalName) VALUES(578, 'Solomon Islands');
INSERT INTO UITerms (UITermId, InternalName) VALUES(579, 'Somalia');
INSERT INTO UITerms (UITermId, InternalName) VALUES(580, 'South Africa');
INSERT INTO UITerms (UITermId, InternalName) VALUES(581, 'South Georgia and the South Sandwich Islands');
INSERT INTO UITerms (UITermId, InternalName) VALUES(582, 'South Sudan');
INSERT INTO UITerms (UITermId, InternalName) VALUES(583, 'Spain');
INSERT INTO UITerms (UITermId, InternalName) VALUES(584, 'Sri Lanka');
INSERT INTO UITerms (UITermId, InternalName) VALUES(585, 'Sudan');
INSERT INTO UITerms (UITermId, InternalName) VALUES(586, 'Suriname');
INSERT INTO UITerms (UITermId, InternalName) VALUES(587, 'Svalbard and Jan Mayen');
INSERT INTO UITerms (UITermId, InternalName) VALUES(588, 'Sweden');
INSERT INTO UITerms (UITermId, InternalName) VALUES(589, 'Switzerland');
INSERT INTO UITerms (UITermId, InternalName) VALUES(590, 'Syrian Arab Republic');
INSERT INTO UITerms (UITermId, InternalName) VALUES(591, 'Taiwan, Province of China');
INSERT INTO UITerms (UITermId, InternalName) VALUES(592, 'Tajikistan');
INSERT INTO UITerms (UITermId, InternalName) VALUES(593, 'Tanzania, United Republic of');
INSERT INTO UITerms (UITermId, InternalName) VALUES(594, 'Thailand');
INSERT INTO UITerms (UITermId, InternalName) VALUES(595, 'Timor-Leste');
INSERT INTO UITerms (UITermId, InternalName) VALUES(596, 'Togo');
INSERT INTO UITerms (UITermId, InternalName) VALUES(597, 'Tokelau');
INSERT INTO UITerms (UITermId, InternalName) VALUES(598, 'Tonga');
INSERT INTO UITerms (UITermId, InternalName) VALUES(599, 'Trinidad and Tobago');
INSERT INTO UITerms (UITermId, InternalName) VALUES(600, 'Tunisia');
INSERT INTO UITerms (UITermId, InternalName) VALUES(601, 'Turkey');
INSERT INTO UITerms (UITermId, InternalName) VALUES(602, 'Turkmenistan');
INSERT INTO UITerms (UITermId, InternalName) VALUES(603, 'Turks and Caicos Islands');
INSERT INTO UITerms (UITermId, InternalName) VALUES(604, 'Tuvalu');
INSERT INTO UITerms (UITermId, InternalName) VALUES(605, 'Uganda');
INSERT INTO UITerms (UITermId, InternalName) VALUES(606, 'Ukraine');
INSERT INTO UITerms (UITermId, InternalName) VALUES(607, 'United Arab Emirates');
INSERT INTO UITerms (UITermId, InternalName) VALUES(608, 'United Kingdom of Great Britain and Northern Ireland');
INSERT INTO UITerms (UITermId, InternalName) VALUES(609, 'United States of America');
INSERT INTO UITerms (UITermId, InternalName) VALUES(610, 'United States Minor Outlying Islands');
INSERT INTO UITerms (UITermId, InternalName) VALUES(611, 'Uruguay');
INSERT INTO UITerms (UITermId, InternalName) VALUES(612, 'Uzbekistan');
INSERT INTO UITerms (UITermId, InternalName) VALUES(613, 'Vanuatu');
INSERT INTO UITerms (UITermId, InternalName) VALUES(614, 'Venezuela (Bolivarian Republic of)');
INSERT INTO UITerms (UITermId, InternalName) VALUES(615, 'Viet Nam');
INSERT INTO UITerms (UITermId, InternalName) VALUES(616, 'Virgin Islands (British)');
INSERT INTO UITerms (UITermId, InternalName) VALUES(617, 'Virgin Islands (U.S.)');
INSERT INTO UITerms (UITermId, InternalName) VALUES(618, 'Wallis and Futuna');
INSERT INTO UITerms (UITermId, InternalName) VALUES(619, 'Western Sahara');
INSERT INTO UITerms (UITermId, InternalName) VALUES(620, 'Yemen');
INSERT INTO UITerms (UITermId, InternalName) VALUES(621, 'Zambia');
INSERT INTO UITerms (UITermId, InternalName) VALUES(622, 'Zimbabwe');
INSERT INTO UITerms (UITermId, InternalName) VALUES(623, 'My content');
INSERT INTO UITerms (UITermId, InternalName) VALUES(624, 'My calendar');
INSERT INTO UITerms (UITermId, InternalName) VALUES(625, 'Add appointment');
INSERT INTO UITerms (UITermId, InternalName) VALUES(626, 'My projects');
INSERT INTO UITerms (UITermId, InternalName) VALUES(627, 'Add projects');
INSERT INTO UITerms (UITermId, InternalName) VALUES(628, 'My relations');
INSERT INTO UITerms (UITermId, InternalName) VALUES(629, 'New chat');
INSERT INTO UITerms (UITermId, InternalName) VALUES(630, 'Conferences');
INSERT INTO UITerms (UITermId, InternalName) VALUES(631, 'New conference');
INSERT INTO UITerms (UITermId, InternalName) VALUES(632, 'My favorites');
INSERT INTO UITerms (UITermId, InternalName) VALUES(633, 'Open game');
INSERT INTO UITerms (UITermId, InternalName) VALUES(634, 'Search workflow');
INSERT INTO UITerms (UITermId, InternalName) VALUES(635, 'New workflow');
INSERT INTO UITerms (UITermId, InternalName) VALUES(636, 'Content search');
INSERT INTO UITerms (UITermId, InternalName) VALUES(637, 'Project search');
INSERT INTO UITerms (UITermId, InternalName) VALUES(638, 'People search');
INSERT INTO UITerms (UITermId, InternalName) VALUES(639, 'User defined menu');
INSERT INTO UITerms (UITermId, InternalName) VALUES(640, 'My organizations');
INSERT INTO UITerms (UITermId, InternalName) VALUES(641, 'Classification Master');
INSERT INTO UITerms (UITermId, InternalName) VALUES(642, 'Read classification');
INSERT INTO UITerms (UITermId, InternalName) VALUES(643, 'Update classification');
INSERT INTO UITerms (UITermId, InternalName) VALUES(644, 'Create classification');
INSERT INTO UITerms (UITermId, InternalName) VALUES(645, 'Primary subject');
INSERT INTO UITerms (UITermId, InternalName) VALUES(646, 'Text');
INSERT INTO UITerms (UITermId, InternalName) VALUES(647, 'Number');
INSERT INTO UITerms (UITermId, InternalName) VALUES(648, 'Date time');
INSERT INTO UITerms (UITermId, InternalName) VALUES(649, 'From date');
INSERT INTO UITerms (UITermId, InternalName) VALUES(650, 'To date');
INSERT INTO UITerms (UITermId, InternalName) VALUES(651, 'From date time');
INSERT INTO UITerms (UITermId, InternalName) VALUES(652, 'To date time');
INSERT INTO UITerms (UITermId, InternalName) VALUES(653, 'Action button');
INSERT INTO UITerms (UITermId, InternalName) VALUES(654, 'Cancel button');
INSERT INTO UITerms (UITermId, InternalName) VALUES(655, 'Primary user');
INSERT INTO UITerms (UITermId, InternalName) VALUES(656, 'Secondary user');
INSERT INTO UITerms (UITermId, InternalName) VALUES(657, 'Primary organization');
INSERT INTO UITerms (UITermId, InternalName) VALUES(658, 'Secondary organization');
INSERT INTO UITerms (UITermId, InternalName) VALUES(659, 'Primary project');
INSERT INTO UITerms (UITermId, InternalName) VALUES(660, 'Secondary project');
INSERT INTO UITerms (UITermId, InternalName) VALUES(661, 'Primary language');
INSERT INTO UITerms (UITermId, InternalName) VALUES(662, 'Secondary language');
INSERT INTO UITerms (UITermId, InternalName) VALUES(663, 'Primary classification');
INSERT INTO UITerms (UITermId, InternalName) VALUES(664, 'Secondary classification');
INSERT INTO UITerms (UITermId, InternalName) VALUES(665, 'Primary classification value');
INSERT INTO UITerms (UITermId, InternalName) VALUES(666, 'Secondary classification value');
INSERT INTO UITerms (UITermId, InternalName) VALUES(667, 'Primary content');
INSERT INTO UITerms (UITermId, InternalName) VALUES(668, 'Secondary content');
INSERT INTO UITerms (UITermId, InternalName) VALUES(669, 'Primary country');
INSERT INTO UITerms (UITermId, InternalName) VALUES(670, 'Secondary country');
INSERT INTO UITerms (UITermId, InternalName) VALUES(671, 'Primary security level');
INSERT INTO UITerms (UITermId, InternalName) VALUES(672, 'Secondary security level');
INSERT INTO UITerms (UITermId, InternalName) VALUES(673, 'Primary role');
INSERT INTO UITerms (UITermId, InternalName) VALUES(674, 'Secondary role');
INSERT INTO UITerms (UITermId, InternalName) VALUES(675, 'HTML text');
INSERT INTO UITerms (UITermId, InternalName) VALUES(676, 'Mailing address');
INSERT INTO UITerms (UITermId, InternalName) VALUES(677, 'Phone');
INSERT INTO UITerms (UITermId, InternalName) VALUES(678, 'Skype');
INSERT INTO UITerms (UITermId, InternalName) VALUES(679, 'Hide');
INSERT INTO UITerms (UITermId, InternalName) VALUES(680, 'Disabled');
INSERT INTO UITerms (UITermId, InternalName) VALUES(681, 'Editable');
INSERT INTO UITerms (UITermId, InternalName) VALUES(682, 'Mandatory');
INSERT INTO UITerms (UITermId, InternalName) VALUES(683, 'Level 1');
INSERT INTO UITerms (UITermId, InternalName) VALUES(684, 'Level 2');
INSERT INTO UITerms (UITermId, InternalName) VALUES(685, 'Level 3');
INSERT INTO UITerms (UITermId, InternalName) VALUES(686, 'Level 4');
INSERT INTO UITerms (UITermId, InternalName) VALUES(687, 'Level 5');
INSERT INTO UITerms (UITermId, InternalName) VALUES(688, 'Level 6');
INSERT INTO UITerms (UITermId, InternalName) VALUES(689, 'Level 7');
INSERT INTO UITerms (UITermId, InternalName) VALUES(690, 'Level 8');
INSERT INTO UITerms (UITermId, InternalName) VALUES(691, 'Level 9');
INSERT INTO UITerms (UITermId, InternalName) VALUES(692, 'Level 10');
INSERT INTO UITerms (UITermId, InternalName) VALUES(693, 'Abkhazian');
INSERT INTO UITerms (UITermId, InternalName) VALUES(694, 'Afar');
INSERT INTO UITerms (UITermId, InternalName) VALUES(695, 'Afrikaans');
INSERT INTO UITerms (UITermId, InternalName) VALUES(696, 'Akan');
INSERT INTO UITerms (UITermId, InternalName) VALUES(697, 'Albanian');
INSERT INTO UITerms (UITermId, InternalName) VALUES(698, 'Amharic');
INSERT INTO UITerms (UITermId, InternalName) VALUES(699, 'Arabic');
INSERT INTO UITerms (UITermId, InternalName) VALUES(700, 'Aragonese');
INSERT INTO UITerms (UITermId, InternalName) VALUES(701, 'Armenian');
INSERT INTO UITerms (UITermId, InternalName) VALUES(702, 'Assamese');
INSERT INTO UITerms (UITermId, InternalName) VALUES(703, 'Avaric');
INSERT INTO UITerms (UITermId, InternalName) VALUES(704, 'Avestan');
INSERT INTO UITerms (UITermId, InternalName) VALUES(705, 'Aymara');
INSERT INTO UITerms (UITermId, InternalName) VALUES(706, 'Azerbaijani');
INSERT INTO UITerms (UITermId, InternalName) VALUES(707, 'Bambara');
INSERT INTO UITerms (UITermId, InternalName) VALUES(708, 'Bashkir');
INSERT INTO UITerms (UITermId, InternalName) VALUES(709, 'Basque');
INSERT INTO UITerms (UITermId, InternalName) VALUES(710, 'Belarusian');
INSERT INTO UITerms (UITermId, InternalName) VALUES(711, 'Bengali');
INSERT INTO UITerms (UITermId, InternalName) VALUES(712, 'Bihari languages');
INSERT INTO UITerms (UITermId, InternalName) VALUES(713, 'Bislama');
INSERT INTO UITerms (UITermId, InternalName) VALUES(714, 'Bosnian');
INSERT INTO UITerms (UITermId, InternalName) VALUES(715, 'Breton');
INSERT INTO UITerms (UITermId, InternalName) VALUES(716, 'Bulgarian');
INSERT INTO UITerms (UITermId, InternalName) VALUES(717, 'Burmese');
INSERT INTO UITerms (UITermId, InternalName) VALUES(718, 'Catalan, Valencian');
INSERT INTO UITerms (UITermId, InternalName) VALUES(719, 'Chamorro');
INSERT INTO UITerms (UITermId, InternalName) VALUES(720, 'Chechen');
INSERT INTO UITerms (UITermId, InternalName) VALUES(721, 'Chichewa, Chewa, Nyanja');
INSERT INTO UITerms (UITermId, InternalName) VALUES(722, 'Chinese');
INSERT INTO UITerms (UITermId, InternalName) VALUES(723, 'Chuvash');
INSERT INTO UITerms (UITermId, InternalName) VALUES(724, 'Cornish');
INSERT INTO UITerms (UITermId, InternalName) VALUES(725, 'Corsican');
INSERT INTO UITerms (UITermId, InternalName) VALUES(726, 'Cree');
INSERT INTO UITerms (UITermId, InternalName) VALUES(727, 'Croatian');
INSERT INTO UITerms (UITermId, InternalName) VALUES(728, 'Czech');
INSERT INTO UITerms (UITermId, InternalName) VALUES(729, 'Danish');
INSERT INTO UITerms (UITermId, InternalName) VALUES(730, 'Divehi, Dhivehi, Maldivian');
INSERT INTO UITerms (UITermId, InternalName) VALUES(731, 'Dutch, Flemish');
INSERT INTO UITerms (UITermId, InternalName) VALUES(732, 'Dzongkha');
INSERT INTO UITerms (UITermId, InternalName) VALUES(733, 'English');
INSERT INTO UITerms (UITermId, InternalName) VALUES(734, 'Esperanto');
INSERT INTO UITerms (UITermId, InternalName) VALUES(735, 'Estonian');
INSERT INTO UITerms (UITermId, InternalName) VALUES(736, 'Ewe');
INSERT INTO UITerms (UITermId, InternalName) VALUES(737, 'Faroese');
INSERT INTO UITerms (UITermId, InternalName) VALUES(738, 'Fijian');
INSERT INTO UITerms (UITermId, InternalName) VALUES(739, 'Finnish');
INSERT INTO UITerms (UITermId, InternalName) VALUES(740, 'French');
INSERT INTO UITerms (UITermId, InternalName) VALUES(741, 'Fulah');
INSERT INTO UITerms (UITermId, InternalName) VALUES(742, 'Galician');
INSERT INTO UITerms (UITermId, InternalName) VALUES(743, 'Georgian');
INSERT INTO UITerms (UITermId, InternalName) VALUES(744, 'German');
INSERT INTO UITerms (UITermId, InternalName) VALUES(745, 'Greek, Modern (1453-)');
INSERT INTO UITerms (UITermId, InternalName) VALUES(746, 'Guarani');
INSERT INTO UITerms (UITermId, InternalName) VALUES(747, 'Gujarati');
INSERT INTO UITerms (UITermId, InternalName) VALUES(748, 'Haitian, Haitian Creole');
INSERT INTO UITerms (UITermId, InternalName) VALUES(749, 'Hausa');
INSERT INTO UITerms (UITermId, InternalName) VALUES(750, 'Hebrew');
INSERT INTO UITerms (UITermId, InternalName) VALUES(751, 'Herero');
INSERT INTO UITerms (UITermId, InternalName) VALUES(752, 'Hindi');
INSERT INTO UITerms (UITermId, InternalName) VALUES(753, 'Hiri Motu');
INSERT INTO UITerms (UITermId, InternalName) VALUES(754, 'Hungarian');
INSERT INTO UITerms (UITermId, InternalName) VALUES(755, 'Interlingua');
INSERT INTO UITerms (UITermId, InternalName) VALUES(756, 'Indonesian');
INSERT INTO UITerms (UITermId, InternalName) VALUES(757, 'Interlingue, Occidental');
INSERT INTO UITerms (UITermId, InternalName) VALUES(758, 'Irish');
INSERT INTO UITerms (UITermId, InternalName) VALUES(759, 'Igbo');
INSERT INTO UITerms (UITermId, InternalName) VALUES(760, 'Inupiaq');
INSERT INTO UITerms (UITermId, InternalName) VALUES(761, 'Ido');
INSERT INTO UITerms (UITermId, InternalName) VALUES(762, 'Icelandic');
INSERT INTO UITerms (UITermId, InternalName) VALUES(763, 'Italian');
INSERT INTO UITerms (UITermId, InternalName) VALUES(764, 'Inuktitut');
INSERT INTO UITerms (UITermId, InternalName) VALUES(765, 'Japanese');
INSERT INTO UITerms (UITermId, InternalName) VALUES(766, 'Javanese');
INSERT INTO UITerms (UITermId, InternalName) VALUES(767, 'Kalaallisut, Greenlandic');
INSERT INTO UITerms (UITermId, InternalName) VALUES(768, 'Kannada');
INSERT INTO UITerms (UITermId, InternalName) VALUES(769, 'Kanuri');
INSERT INTO UITerms (UITermId, InternalName) VALUES(770, 'Kashmiri');
INSERT INTO UITerms (UITermId, InternalName) VALUES(771, 'Kazakh');
INSERT INTO UITerms (UITermId, InternalName) VALUES(772, 'Central Khmer');
INSERT INTO UITerms (UITermId, InternalName) VALUES(773, 'Kikuyu, Gikuyu');
INSERT INTO UITerms (UITermId, InternalName) VALUES(774, 'Kinyarwanda');
INSERT INTO UITerms (UITermId, InternalName) VALUES(775, 'Kirghiz, Kyrgyz');
INSERT INTO UITerms (UITermId, InternalName) VALUES(776, 'Komi');
INSERT INTO UITerms (UITermId, InternalName) VALUES(777, 'Kongo');
INSERT INTO UITerms (UITermId, InternalName) VALUES(778, 'Korean');
INSERT INTO UITerms (UITermId, InternalName) VALUES(779, 'Kurdish');
INSERT INTO UITerms (UITermId, InternalName) VALUES(780, 'Kuanyama, Kwanyama');
INSERT INTO UITerms (UITermId, InternalName) VALUES(781, 'Latin');
INSERT INTO UITerms (UITermId, InternalName) VALUES(782, 'Luxembourgish, Letzeburgesch');
INSERT INTO UITerms (UITermId, InternalName) VALUES(783, 'Ganda');
INSERT INTO UITerms (UITermId, InternalName) VALUES(784, 'Limburgan, Limburger, Limburgish');
INSERT INTO UITerms (UITermId, InternalName) VALUES(785, 'Lingala');
INSERT INTO UITerms (UITermId, InternalName) VALUES(786, 'Lao');
INSERT INTO UITerms (UITermId, InternalName) VALUES(787, 'Lithuanian');
INSERT INTO UITerms (UITermId, InternalName) VALUES(788, 'Luba-Katanga');
INSERT INTO UITerms (UITermId, InternalName) VALUES(789, 'Latvian');
INSERT INTO UITerms (UITermId, InternalName) VALUES(790, 'Manx');
INSERT INTO UITerms (UITermId, InternalName) VALUES(791, 'Macedonian');
INSERT INTO UITerms (UITermId, InternalName) VALUES(792, 'Malagasy');
INSERT INTO UITerms (UITermId, InternalName) VALUES(793, 'Malay');
INSERT INTO UITerms (UITermId, InternalName) VALUES(794, 'Malayalam');
INSERT INTO UITerms (UITermId, InternalName) VALUES(795, 'Maltese');
INSERT INTO UITerms (UITermId, InternalName) VALUES(796, 'Maori');
INSERT INTO UITerms (UITermId, InternalName) VALUES(797, 'Marathi');
INSERT INTO UITerms (UITermId, InternalName) VALUES(798, 'Marshallese');
INSERT INTO UITerms (UITermId, InternalName) VALUES(799, 'Mongolian');
INSERT INTO UITerms (UITermId, InternalName) VALUES(800, 'Nauru');
INSERT INTO UITerms (UITermId, InternalName) VALUES(801, 'Navajo, Navaho');
INSERT INTO UITerms (UITermId, InternalName) VALUES(802, 'North Ndebele');
INSERT INTO UITerms (UITermId, InternalName) VALUES(803, 'Nepali');
INSERT INTO UITerms (UITermId, InternalName) VALUES(804, 'Ndonga');
INSERT INTO UITerms (UITermId, InternalName) VALUES(805, 'Norwegian Bokmål');
INSERT INTO UITerms (UITermId, InternalName) VALUES(806, 'Norwegian Nynorsk');
INSERT INTO UITerms (UITermId, InternalName) VALUES(807, 'Norwegian');
INSERT INTO UITerms (UITermId, InternalName) VALUES(808, 'Sichuan Yi, Nuosu');
INSERT INTO UITerms (UITermId, InternalName) VALUES(809, 'South Ndebele');
INSERT INTO UITerms (UITermId, InternalName) VALUES(810, 'Occitan');
INSERT INTO UITerms (UITermId, InternalName) VALUES(811, 'Ojibwa');
INSERT INTO UITerms (UITermId, InternalName) VALUES(812, 'Church Slavic, Old Slavonic, Church Slavonic');
INSERT INTO UITerms (UITermId, InternalName) VALUES(813, 'Oromo');
INSERT INTO UITerms (UITermId, InternalName) VALUES(814, 'Oriya');
INSERT INTO UITerms (UITermId, InternalName) VALUES(815, 'Ossetian, Ossetic');
INSERT INTO UITerms (UITermId, InternalName) VALUES(816, 'Punjabi, Panjabi');
INSERT INTO UITerms (UITermId, InternalName) VALUES(817, 'Pali');
INSERT INTO UITerms (UITermId, InternalName) VALUES(818, 'Persian');
INSERT INTO UITerms (UITermId, InternalName) VALUES(819, 'Polish');
INSERT INTO UITerms (UITermId, InternalName) VALUES(820, 'Pashto, Pushto');
INSERT INTO UITerms (UITermId, InternalName) VALUES(821, 'Portuguese');
INSERT INTO UITerms (UITermId, InternalName) VALUES(822, 'Quechua');
INSERT INTO UITerms (UITermId, InternalName) VALUES(823, 'Romansh');
INSERT INTO UITerms (UITermId, InternalName) VALUES(824, 'Rundi');
INSERT INTO UITerms (UITermId, InternalName) VALUES(825, 'Romanian, Moldavian, Moldovan');
INSERT INTO UITerms (UITermId, InternalName) VALUES(826, 'Russian');
INSERT INTO UITerms (UITermId, InternalName) VALUES(827, 'Sanskrit');
INSERT INTO UITerms (UITermId, InternalName) VALUES(828, 'Sardinian');
INSERT INTO UITerms (UITermId, InternalName) VALUES(829, 'Sindhi');
INSERT INTO UITerms (UITermId, InternalName) VALUES(830, 'Northern Sami');
INSERT INTO UITerms (UITermId, InternalName) VALUES(831, 'Samoan');
INSERT INTO UITerms (UITermId, InternalName) VALUES(832, 'Sango');
INSERT INTO UITerms (UITermId, InternalName) VALUES(833, 'Serbian');
INSERT INTO UITerms (UITermId, InternalName) VALUES(834, 'Gaelic, Scottish Gaelic');
INSERT INTO UITerms (UITermId, InternalName) VALUES(835, 'Shona');
INSERT INTO UITerms (UITermId, InternalName) VALUES(836, 'Sinhala, Sinhalese');
INSERT INTO UITerms (UITermId, InternalName) VALUES(837, 'Slovak');
INSERT INTO UITerms (UITermId, InternalName) VALUES(838, 'Slovenian');
INSERT INTO UITerms (UITermId, InternalName) VALUES(839, 'Somali');
INSERT INTO UITerms (UITermId, InternalName) VALUES(840, 'Southern Sotho');
INSERT INTO UITerms (UITermId, InternalName) VALUES(841, 'Spanish, Castilian');
INSERT INTO UITerms (UITermId, InternalName) VALUES(842, 'Sundanese');
INSERT INTO UITerms (UITermId, InternalName) VALUES(843, 'Swahili');
INSERT INTO UITerms (UITermId, InternalName) VALUES(844, 'Swati');
INSERT INTO UITerms (UITermId, InternalName) VALUES(845, 'Swedish');
INSERT INTO UITerms (UITermId, InternalName) VALUES(846, 'Tamil');
INSERT INTO UITerms (UITermId, InternalName) VALUES(847, 'Telugu');
INSERT INTO UITerms (UITermId, InternalName) VALUES(848, 'Tajik');
INSERT INTO UITerms (UITermId, InternalName) VALUES(849, 'Thai');
INSERT INTO UITerms (UITermId, InternalName) VALUES(850, 'Tigrinya');
INSERT INTO UITerms (UITermId, InternalName) VALUES(851, 'Tibetan');
INSERT INTO UITerms (UITermId, InternalName) VALUES(852, 'Turkmen');
INSERT INTO UITerms (UITermId, InternalName) VALUES(853, 'Tagalog');
INSERT INTO UITerms (UITermId, InternalName) VALUES(854, 'Tswana');
INSERT INTO UITerms (UITermId, InternalName) VALUES(855, 'Tonga (Tonga Islands)');
INSERT INTO UITerms (UITermId, InternalName) VALUES(856, 'Turkish');
INSERT INTO UITerms (UITermId, InternalName) VALUES(857, 'Tsonga');
INSERT INTO UITerms (UITermId, InternalName) VALUES(858, 'Tatar');
INSERT INTO UITerms (UITermId, InternalName) VALUES(859, 'Twi');
INSERT INTO UITerms (UITermId, InternalName) VALUES(860, 'Tahitian');
INSERT INTO UITerms (UITermId, InternalName) VALUES(861, 'Uighur, Uyghur');
INSERT INTO UITerms (UITermId, InternalName) VALUES(862, 'Ukrainian');
INSERT INTO UITerms (UITermId, InternalName) VALUES(863, 'Urdu');
INSERT INTO UITerms (UITermId, InternalName) VALUES(864, 'Uzbek');
INSERT INTO UITerms (UITermId, InternalName) VALUES(865, 'Venda');
INSERT INTO UITerms (UITermId, InternalName) VALUES(866, 'Vietnamese');
INSERT INTO UITerms (UITermId, InternalName) VALUES(867, 'Volapük');
INSERT INTO UITerms (UITermId, InternalName) VALUES(868, 'Walloon');
INSERT INTO UITerms (UITermId, InternalName) VALUES(869, 'Welsh');
INSERT INTO UITerms (UITermId, InternalName) VALUES(870, 'Wolof');
INSERT INTO UITerms (UITermId, InternalName) VALUES(871, 'Western Frisian');
INSERT INTO UITerms (UITermId, InternalName) VALUES(872, 'Xhosa');
INSERT INTO UITerms (UITermId, InternalName) VALUES(873, 'Yiddish');
INSERT INTO UITerms (UITermId, InternalName) VALUES(874, 'Yoruba');
INSERT INTO UITerms (UITermId, InternalName) VALUES(875, 'Zhuang, Chuang');
INSERT INTO UITerms (UITermId, InternalName) VALUES(876, 'Zulu');
INSERT INTO UITerms (UITermId, InternalName) VALUES(877, 'Male');
INSERT INTO UITerms (UITermId, InternalName) VALUES(878, 'Female');
INSERT INTO UITerms (UITermId, InternalName) VALUES(879, 'Trans');
INSERT INTO UITerms (UITermId, InternalName) VALUES(880, 'Creator is user');
INSERT INTO UITerms (UITermId, InternalName) VALUES(881, 'If the primary user is the creator');
INSERT INTO UITerms (UITermId, InternalName) VALUES(882, 'Field');
INSERT INTO UITerms (UITermId, InternalName) VALUES(883, 'If the field has the value of the condition');
INSERT INTO UITerms (UITermId, InternalName) VALUES(884, 'Security level user');
INSERT INTO UITerms (UITermId, InternalName) VALUES(885, 'Compare the security level with field');
INSERT INTO UITerms (UITermId, InternalName) VALUES(886, 'Role user');
INSERT INTO UITerms (UITermId, InternalName) VALUES(887, 'Check if the user has a role compared with role field');
INSERT INTO UITerms (UITermId, InternalName) VALUES(888, 'Manager user field');
INSERT INTO UITerms (UITermId, InternalName) VALUES(889, 'Manager of the primary user field');
INSERT INTO UITerms (UITermId, InternalName) VALUES(890, 'Organization user');
INSERT INTO UITerms (UITermId, InternalName) VALUES(891, 'User is a member of the organization');
INSERT INTO UITerms (UITermId, InternalName) VALUES(892, 'Organization role user');
INSERT INTO UITerms (UITermId, InternalName) VALUES(893, 'User has a specific role in the organization');
INSERT INTO UITerms (UITermId, InternalName) VALUES(894, 'Organization parent user');
INSERT INTO UITerms (UITermId, InternalName) VALUES(895, 'User is a member of the organization or sub organizations');
INSERT INTO UITerms (UITermId, InternalName) VALUES(896, 'Organization parent role user');
INSERT INTO UITerms (UITermId, InternalName) VALUES(897, 'User has a specific role in the organization or sub organizations');
INSERT INTO UITerms (UITermId, InternalName) VALUES(898, 'Project user');
INSERT INTO UITerms (UITermId, InternalName) VALUES(899, 'User is a member of the project');
INSERT INTO UITerms (UITermId, InternalName) VALUES(900, 'Project role user');
INSERT INTO UITerms (UITermId, InternalName) VALUES(901, 'User has a specific role in the project');
INSERT INTO UITerms (UITermId, InternalName) VALUES(902, 'Project parent user');
INSERT INTO UITerms (UITermId, InternalName) VALUES(903, 'User is a member of the project or sub projects');
INSERT INTO UITerms (UITermId, InternalName) VALUES(904, 'Project parent role user');
INSERT INTO UITerms (UITermId, InternalName) VALUES(905, 'User has a specific role in the project or sub projects');
INSERT INTO UITerms (UITermId, InternalName) VALUES(906, 'Default organization user');
INSERT INTO UITerms (UITermId, InternalName) VALUES(907, 'The default organization of the user is equal to the primary org field');
INSERT INTO UITerms (UITermId, InternalName) VALUES(908, 'Open bracket');
INSERT INTO UITerms (UITermId, InternalName) VALUES(909, 'Used for complex conditions');
INSERT INTO UITerms (UITermId, InternalName) VALUES(910, 'and');
INSERT INTO UITerms (UITermId, InternalName) VALUES(911, 'or');
INSERT INTO UITerms (UITermId, InternalName) VALUES(912, 'Close bracket');
INSERT INTO UITerms (UITermId, InternalName) VALUES(913, 'User');
INSERT INTO UITerms (UITermId, InternalName) VALUES(914, 'The user is equal to the primary user field');
INSERT INTO UITerms (UITermId, InternalName) VALUES(915, 'Relation to creator');
INSERT INTO UITerms (UITermId, InternalName) VALUES(916, 'The user has a specific relation to the creator');
INSERT INTO UITerms (UITermId, InternalName) VALUES(917, 'Relation to user field');
INSERT INTO UITerms (UITermId, InternalName) VALUES(918, 'The user has a specific relation to the user field');
INSERT INTO UITerms (UITermId, InternalName) VALUES(919, 'Organization role');
INSERT INTO UITerms (UITermId, InternalName) VALUES(920, 'Project role');
SET IDENTITY_INSERT UITerms OFF;

SET IDENTITY_INSERT SecurityLevels ON;
INSERT INTO SecurityLevels (SecurityLevelID, NameTermID, DescriptionTermID, MenuNameTermID, MouseOverTermID) VALUES 
  (1,688,688,688,688)
, (2,689,689,689,689)
, (3,690,690,690,690)
, (4,691,691,691,691)
, (5,692,692,692,692)
, (6,693,693,693,693)
, (7,694,694,694,694)
, (8,695,695,695,695)
, (9,696,696,696,696)
, (10,697,697,697,697)
SET IDENTITY_INSERT SecurityLevels OFF;
