CREATE PROCEDURE [dbo].[usp_ClassificationPageSectionLanguageDelete] (@ClassificationPageSectionLanguageID int) 
AS 
DELETE FROM ClassificationPageSectionLanguages WHERE ClassificationPageSectionLanguageID= @ClassificationPageSectionLanguageID