CREATE PROCEDURE usp_ProcessTemplateFlowConditionDeletePost (@ProcessTemplateFlowConditionId int)
AS
SET XACT_ABORT ON;
BEGIN TRANSACTION

DELETE FROM ProcessTemplateFlowConditionLanguages WHERE ProcessTemplateFlowConditionId = @ProcessTemplateFlowConditionId
DELETE FROM ProcessTemplateFlowConditions WHERE ProcessTemplateFlowConditionId = @ProcessTemplateFlowConditionId

COMMIT TRANSACTION
