CREATE PROCEDURE usp_ClassificationValueForPanelCondition (@PageSectionId int)
AS
SELECT PageSectionClassificationValueConditionId
	, PageSectionClassificationValueConditionTypeId 
	,PageSectionClassificationValueConditionInt
	,PageSectionClassificationValueConditionString
	,PageSectionClassificationValueConditionDate
FROM PageSectionClassificationValueConditions 
WHERE pagesectionid = @PageSectionId