CREATE PROCEDURE usp_PageDeletePost ( @UserId nvarchar(450), @PageId int)
AS
SET XACT_ABORT ON;
BEGIN TRANSACTION
DELETE FROM PageLanguages 
WHERE PageID  = @PageId 

DELETE FROM Pages 
WHERE PageID = @PageId
COMMIT TRANSACTION