CREATE PROCEDURE [dbo].[usp_MetaListProcessTemplateFlowConditionComparisonOperators]
AS
SELECT ProcessTemplateFlowConditionComparisonOperators.ProcessTemplateFlowConditionComparisonOperatorId, Name
FROM ProcessTemplateFlowConditionComparisonOperators 
JOIN UITermLanguages
	ON ProcessTemplateFlowConditionComparisonOperators.NameTermId = UITermLanguages.UITermID
WHERE LanguageId =41 
ORDER BY Name