CREATE PROCEDURE usp_NewProcessGetInitialTemplateFlowConditionList (@ProcessTypeFlowId int)
AS
SELECT ProcessTypeFlowConditions.ProcessTypeFlowConditionID
	, ProcessTypeFlowConditions.ProcessTypeFlowConditionTypeID
	, ProcessTypeFlowConditions.ProcessTypeFieldID
	, ProcessTypeFlowConditions.ProcessTypeFieldIDRole
	, ProcessTypeFlowConditions.ComparisonOperatorID
	, ProcessTypeFlowConditions.ProcessTypeFlowConditionString
	, ProcessTypeFlowConditions.ProcessTypeFlowConditionInt
	, ProcessTypeFlowConditions.ProcessTypeFlowConditionDate
FROM ProcessTypeFlowConditions 
WHERE ProcessTypeFlowConditions.ProcessTypeFlowID = @ProcessTypeFlowId
ORDER BY Sequence