CREATE PROCEDURE usp_NewProcessGetFlowConditionList (@FlowId int) 
AS
SELECT ProcessTemplateFlowConditions.ProcessTemplateFlowId
	, ProcessTemplateFlowConditions.ProcessTemplateFlowConditionId
	, ProcessTemplateFlowConditions.ProcessTemplateFlowConditionTypeID
	, ProcessTemplateFlowConditions.ProcessTemplateFieldID
	, ProcessTemplateFlowConditions.ProcessTemplateFieldIDRole
	, ProcessTemplateFlowConditions.ComparisonOperatorID
	, ProcessTemplateFlowConditions.ProcessTemplateFlowConditionString
	, ProcessTemplateFlowConditions.ProcessTemplateFlowConditionInt
	, ProcessTemplateFlowConditions.ProcessTemplateFlowConditionDate
FROM ProcessTemplateFlowConditions 
WHERE ProcessTemplateFlowConditions.ProcessTemplateFlowId = @FlowID
ORDER BY Sequence

