CREATE PROCEDURE [dbo].[usp_ClassificationPageSectionLanguageDelete] (@ClassificationPageSectionLanguageId int) 
AS 
DELETE FROM ClassificationPageSectionLanguages WHERE ClassificationPageSectionLanguageID= @ClassificationPageSectionLanguageID